name: terraform-ci
on:
  push:
    branches:
      - "main"
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-action-youtubebackup-session
          aws-region: ap-northeast-1
      
      - run: aws s3 ls youtubedl-bucket


