name: terraform-ci
on:
  push:
    branches:
      - "main"
  
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: session
          aws-region: ap-northeast-1
      # - name: Configure AWS
      #   run: |
      #     export AWS_ROLE_ARN=${{ secrets.ROLE_ARN }}
      #     export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
      #     export AWS_DEFAULT_REGION=ap-northeast-1
      #     echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
      #     echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
      #     echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV
      #     curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
      
      - run: aws s3 ls youtubedl-bucket


