name: terraform-ci
on:
  push:
    branches:
      - "main"
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-action-youtubebackup-session
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - name: Terraform Format
        run: terraform fmt -recursive -check

      - name: Terraform
        run: |
          terraform init
          terraform validate
          terraform plan -var "custome_domain_name=${{ secrets.CUSTOM_DOMAIN_NAME }}" -var "hostzone=${{ secrets.HOSTZONE }}"

